#!/bin/sh
  # Get client and server addresses from the command line
  if  [ -z "$1" ]&&[ -n "$SSH_ORIGINAL_COMMAND" ]; then
  # If nothigh in the command line (forced command) retrieve
  # client and server command from SSH_ORIGINAL_COMMAND variable
  # We need split variable into words during set
  # shellcheck disable=SC2086
  set -- ${SSH_ORIGINAL_COMMAND#* }
  fi
  server="$1"
  client="$2"
  others="$3"
  
  ip addr add "$server" peer "$client" dev "$SSH_TUNNEL"
  ip link set "$SSH_TUNNEL" up
  # set up host routes to additional hosts accessible via this client
  # we need word splitting here
  # shellcheck disable=SC2086
  for host in $others; do
  	ip route add "$host/32" via "$client" dev "$SSH_TUNNEL"
  done	
  # now wait until outher side would break connection
  cat
